name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Python versions are specified in pyproject.toml

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.1

      - name: Build and test wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Only build 64-bit architectures
          
          CIBW_ARCHS: "auto64"

          # Install GDAL before testing MGET. On Linux, install GDAL's Debian
          # package. libgdal-dev appears to also be required, because when
          # MGET is installed, pip fulfills its dependency on the GDAL Python
          # package by installing and building GDAL's sdist, which apparently
          # can't be done without libgdal-dev.
          #
          # On Windows, install the latest GDAL Python package from
          # Christoph Gohlke's collection of geospatial library wheels.

          CIBW_BEFORE_TEST_LINUX: >
            yum install -y gdal libgdal-dev

          # Install dependencies required to run MGET's tests
          
          CIBW_TEST_REQUIRES: pytest python-dotenv

          # Run MGET's tests
          
          CIBW_TEST_COMMAND: "echo Wheel installed"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
