name: Test skfmm

on:
  workflow_dispatch:

jobs:
  test_skfmm_on_windows:
    name: Test skfmm on ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]                # [windows-latest, windows-2022, windows-2019]
        python-version: ["3.11"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install scikit-fmm from PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy<2
          python -m pip install scikit-fmm

      - name: Dump some information
        run: |
          echo "Dumping site-packages directories"
          python -c "import sys; print(sys.path)"
          echo "Finding cfmm*.pyd"
          python -c "import site, glob, os; p = [glob.glob(os.path.join(s, 'skfmm', 'cfmm*.pyd')) for s in site.getsitepackages()]; print([item for sublist in p for item in sublist])"
          echo "Running dumpbin.exe /DEPENDENTS on cfmm*.pyd"

      - name: Try to import skfmm (this will fail)
        run: |
          python -c "import skfmm"
